[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

; --- Mobile Client (2000) ---
[2000]
type=endpoint
context=default
disallow=all
allow=ulaw,alaw,slin,gsm
auth=auth2000
aors=2000
direct_media=no
force_rport=yes
rewrite_contact=yes
rtp_symmetric=yes

[auth2000]
type=auth
auth_type=userpass
password=5678
username=2000

[2000]
type=aor
max_contacts=5
remove_existing=yes

; --- Agent Client (5678) ---
[5678]
type=endpoint
context=default
disallow=all
allow=ulaw,alaw,slin
auth=auth5678
aors=5678
direct_media=no

[auth5678]
type=auth
auth_type=userpass
password=password5678
username=5678

[5678]
type=aor
max_contacts=5
